<?php

namespace App\Entity;

use App\Repository\EDOBillingRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: EDOBillingRepository::class)]
#[ORM\Table(name: 'edo_billings')]
#[ORM\Index(name: 'idx_edo_billing_regen_req', columns: ['regeneration_request_id'])]
#[ORM\Index(name: 'idx_edo_billing_created_at', columns: ['created_at'])]
class EDOBilling
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private ?int $id = null;

    #[ORM\OneToOne(targetEntity: RegenerationRequest::class, inversedBy: 'billing')]
    #[ORM\JoinColumn(name: 'regeneration_request_id', nullable: false, unique: true, onDelete: 'CASCADE')]
    #[Assert\NotNull(message: 'Regeneration request is required')]
    private RegenerationRequest $regenerationRequest;

    #[ORM\Column(type: 'integer')]
    #[Assert\NotNull(message: 'Expired days is required')]
    #[Assert\PositiveOrZero(message: 'Expired days must be zero or positive')]
    private int $expiredDays;

    #[ORM\Column(type: 'decimal', precision: 10, scale: 2)]
    #[Assert\NotNull(message: 'Per day rate is required')]
    #[Assert\Positive(message: 'Per day rate must be positive')]
    private float $perDayRate;

    #[ORM\Column(type: 'decimal', precision: 10, scale: 2)]
    #[Assert\NotNull(message: 'Total amount is required')]
    #[Assert\PositiveOrZero(message: 'Total amount must be zero or positive')]
    private float $totalAmount;

    #[ORM\Column(type: 'string', length: 500, nullable: true)]
    private ?string $billingDocumentPath = null;

    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(nullable: false, onDelete: 'RESTRICT')]
    #[Assert\NotNull(message: 'Generated by user is required')]
    private User $generatedBy;

    #[ORM\Column(type: 'datetime')]
    private \DateTimeInterface $createdAt;

    #[ORM\OneToOne(targetEntity: EDOPaymentReceipt::class, mappedBy: 'billing')]
    private ?EDOPaymentReceipt $payment = null;

    public function __construct()
    {
        $this->createdAt = new \DateTime();
    }

    /**
     * Calculate total amount from expired days and per day rate
     */
    public function calculateTotalAmount(): void
    {
        $this->totalAmount = $this->expiredDays * $this->perDayRate;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRegenerationRequest(): RegenerationRequest
    {
        return $this->regenerationRequest;
    }

    public function setRegenerationRequest(RegenerationRequest $regenerationRequest): self
    {
        $this->regenerationRequest = $regenerationRequest;
        return $this;
    }

    public function getExpiredDays(): int
    {
        return $this->expiredDays;
    }

    public function setExpiredDays(int $expiredDays): self
    {
        $this->expiredDays = $expiredDays;
        return $this;
    }

    public function getPerDayRate(): float
    {
        return $this->perDayRate;
    }

    public function setPerDayRate(float $perDayRate): self
    {
        $this->perDayRate = $perDayRate;
        return $this;
    }

    public function getTotalAmount(): float
    {
        return $this->totalAmount;
    }

    public function setTotalAmount(float $totalAmount): self
    {
        $this->totalAmount = $totalAmount;
        return $this;
    }

    public function getBillingDocumentPath(): ?string
    {
        return $this->billingDocumentPath;
    }

    public function setBillingDocumentPath(?string $billingDocumentPath): self
    {
        $this->billingDocumentPath = $billingDocumentPath;
        return $this;
    }

    public function getGeneratedBy(): User
    {
        return $this->generatedBy;
    }

    public function setGeneratedBy(User $generatedBy): self
    {
        $this->generatedBy = $generatedBy;
        return $this;
    }

    public function getCreatedAt(): \DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;
        return $this;
    }

    public function getPayment(): ?EDOPaymentReceipt
    {
        return $this->payment;
    }

    public function setPayment(?EDOPaymentReceipt $payment): self
    {
        $this->payment = $payment;
        return $this;
    }
}
