<?php

namespace App\Form;

use App\Entity\Enum\DocumentTemplateType;
use App\Service\OfficialReceiptLayoutAdapter;

/**
 * Registry of document template block types, placeholders, and default layouts.
 */
class DocumentBlockTypes
{
    public const ALL = [
        'header_banner',
        'heading',
        'text',
        'placeholder',
        'field_label',
        'field_value',
        'info_row',
        'divider',
        'spacer',
        'image',
        'logo',
        'table',
        'signature',
        'qr_code',
        'border_box',
        'two_column',
        'footer',
    ];

    public static function templateGroups(): array
    {
        return [
            'Headers & Titles' => [
                'header_banner' => ['icon' => 'icon-[tabler--layout-navbar]', 'name' => 'Header Banner'],
                'heading' => ['icon' => 'icon-[tabler--heading]', 'name' => 'Heading'],
                'logo' => ['icon' => 'icon-[tabler--photo]', 'name' => 'Logo'],
            ],
            'Content' => [
                'text' => ['icon' => 'icon-[tabler--align-left]', 'name' => 'Text Block'],
                'field_label' => ['icon' => 'icon-[tabler--tag]', 'name' => 'Field Label'],
                'field_value' => ['icon' => 'icon-[tabler--variable]', 'name' => 'Field Value'],
                'placeholder' => ['icon' => 'icon-[tabler--variable]', 'name' => 'Dynamic Field'],
                'info_row' => ['icon' => 'icon-[tabler--list-details]', 'name' => 'Label + Value (combined)'],
                'two_column' => ['icon' => 'icon-[tabler--columns]', 'name' => 'Two Columns'],
            ],
            'Data Tables' => [
                'table' => ['icon' => 'icon-[tabler--table]', 'name' => 'Data Table'],
            ],
            'Layout' => [
                'divider' => ['icon' => 'icon-[tabler--separator]', 'name' => 'Divider'],
                'spacer' => ['icon' => 'icon-[tabler--spacing-vertical]', 'name' => 'Spacer'],
                'border_box' => ['icon' => 'icon-[tabler--border-outer]', 'name' => 'Border Box'],
            ],
            'Signatures & Codes' => [
                'signature' => ['icon' => 'icon-[tabler--signature]', 'name' => 'Signature Block'],
                'qr_code' => ['icon' => 'icon-[tabler--qrcode]', 'name' => 'QR Code'],
                'image' => ['icon' => 'icon-[tabler--photo-up]', 'name' => 'Image'],
            ],
            'Footer' => [
                'footer' => ['icon' => 'icon-[tabler--layout-bottombar]', 'name' => 'Footer'],
            ],
        ];
    }

    public static function placeholdersForType(DocumentTemplateType $type): array
    {
        return match ($type) {
            DocumentTemplateType::NOA => [
                'Document' => [
                    'noa.number' => 'NOA Number',
                    'noa.bl_number' => 'BL Number',
                    'noa.vessel_number' => 'Vessel Number',
                    'noa.eta' => 'ETA',
                    'noa.port_location' => 'Port Location',
                    'noa.container_count' => 'Container Count',
                ],
                'Consignee' => [
                    'consignee.name' => 'Consignee Name',
                    'consignee.email' => 'Consignee Email',
                ],
                'System' => [
                    'generated.date' => 'Generated Date',
                    'generated.by' => 'Generated By',
                    'company.name' => 'Company Name',
                    'document.verification_url' => 'Verification Link (QR Code)',
                ],
                'Tables' => [
                    'containers.table' => 'Containers Table',
                ],
            ],
            DocumentTemplateType::EDO => [
                'Document' => [
                    'edo.status' => 'Document Status',
                    'edo.document_title' => 'Document Title',
                    'edo.document_subtitle' => 'Document Subtitle',
                    'edo.port_directive' => 'Port Operations Directive',
                ],
                'Manifest & Registry' => [
                    'manifest.number' => 'Manifest Number',
                    'manifest.bl_number' => 'BL Number',
                    'noa.number' => 'Registry Number (NOA)',
                ],
                'Parties' => [
                    'consignee.name' => 'Consignee / Notify Party',
                    'broker.name' => 'Broker Name',
                    'shipping.line' => 'Shipping Line / Carrier',
                    'vessel.display' => 'Vessel / Voyage',
                ],
                'Company & Platform' => [
                    'platform.brand' => 'Platform Brand',
                    'platform.tagline' => 'Platform Tagline',
                    'company.name' => 'Company Name',
                ],
                'Signatures' => [
                    'signatures.authorized_title' => 'Authorized Rep. Title',
                    'signatures.authorized_company' => 'Authorized Rep. Company',
                    'signatures.prepared_title' => 'Prepared By Title',
                    'signatures.prepared_by' => 'Prepared By Name',
                    'signatures.received_title' => 'Date/Time Received Title',
                ],
                'Staff' => [
                    'staff.name' => 'Generated By (SL Staff Name)',
                    'staff.role' => 'Staff Role',
                    'edo.generated_by' => 'eDO Generated By Name (stored)',
                ],
                'System' => [
                    'generated.date' => 'Print Date / Time',
                    'generated.datetime' => 'Generated DateTime',
                    'generated.by' => 'Generated By',
                    'document.verification_url' => 'Verification Link (QR Code)',
                ],
                'Tables' => [
                    'containers.table' => 'Containers Table',
                ],
            ],
            DocumentTemplateType::MANIFEST_BL => [
                'Manifest' => [
                    'manifest.number' => 'Manifest Number',
                    'manifest.bl_number' => 'Manifest B/L Number',
                    'manifest.vessel_name' => 'Vessel Name',
                    'manifest.voyage_number' => 'Voyage Number',
                    'manifest.arrival_date' => 'Arrival Date',
                    'manifest.issue_date' => 'Issue Date',
                    'manifest.container_count' => 'Container Count',
                ],
                'Document' => [
                    'noa.number' => 'NOA Number',
                    'noa.bl_number' => 'BL Number',
                    'noa.vessel_number' => 'Vessel Number',
                    'noa.eta' => 'ETA',
                    'noa.port_location' => 'Port Location',
                    'noa.container_count' => 'Container Count',
                ],
                'Consignee' => [
                    'consignee.name' => 'Consignee Name',
                    'consignee.email' => 'Consignee Email',
                ],
                'System' => [
                    'generated.date' => 'Generated Date',
                    'generated.by' => 'Generated By',
                    'company.name' => 'Company Name',
                    'document.verification_url' => 'Verification Link (QR Code)',
                ],
                'Tables' => [
                    'containers.table' => 'Containers Table',
                ],
            ],
            DocumentTemplateType::BILLING => [
                'Invoice' => [
                    'billing.invoice_number' => 'Invoice Number',
                    'billing.invoice_date' => 'Invoice Date',
                    'billing.due_date' => 'Invoice Due Date',
                    'billing.status' => 'Payment Status (e.g. UNPAID)',
                    'billing.currency' => 'Original Currency',
                    'billing.exchange_rate_display' => 'Exchange Rate Display',
                    'billing.amount_primary' => 'Amount (Primary — USD or PHP)',
                    'billing.amount_secondary' => 'Amount (Secondary — PHP conversion)',
                    'billing.amount_header' => 'Amount Header (Primary + Secondary)',
                    'billing.total_amount' => 'Total Amount (PHP)',
                    'billing.total_amount_usd' => 'Total Amount (USD)',
                    'billing.total_amount_display' => 'Total Amount Display (Large PHP)',
                    'billing.freight_charges' => 'Freight Charges (PHP)',
                    'billing.freight_charges_usd' => 'Freight Charges (USD)',
                    'billing.thc_charges' => 'THC Charges (PHP)',
                    'billing.thc_charges_usd' => 'THC Charges (USD)',
                    'billing.additional_charges_total' => 'Additional Charges Total (PHP)',
                    'billing.additional_charges_total_usd' => 'Additional Charges Total (USD)',
                    'billing.additional_charges_count' => 'Additional Charges Count',
                    'billing.note' => 'Payment Note',
                ],
                'Manifest & Consignee' => [
                    'manifest.number' => 'Manifest Number',
                    'manifest.bl_number' => 'BL Number',
                    'consignee.name' => 'Bill To (Consignee Name)',
                    'consignee.email' => 'Consignee Email',
                    'consignee.address' => 'Consignee Address',
                    'broker.name' => 'Broker Name (Processor)',
                    'broker.email' => 'Broker Email (Processor)',
                ],
                'Company' => [
                    'company.name' => 'Company Name',
                    'company.address' => 'Company Address',
                    'company.phone' => 'Company Phone',
                    'company.email' => 'Company Email',
                ],
                'System' => [
                    'generated.date' => 'Generated Date',
                    'generated.by' => 'Generated By',
                    'document.verification_url' => 'Verification Link (QR Code)',
                ],
                'Tables' => [
                    'charges.table' => 'All Line Items (Freight, THC & Additional)',
                    'charges.additional_table' => 'Additional Charges Line Items Only',
                ],
            ],
            DocumentTemplateType::OFFICIAL_RECEIPT => [
                'Official Receipt' => [
                    'receipt.number' => 'Official Receipt Number (OR-########)',
                    'receipt.date' => 'Receipt Date',
                    'receipt.amount' => 'Amount Paid',
                    'receipt.currency' => 'Payment Currency',
                    'receipt.payment_id' => 'Payment ID',
                    'billing.invoice_number' => 'OR Number',
                    'billing.invoice_date' => 'Billing Date',
                    'billing.due_date' => 'Receipt Date',
                    'billing.status' => 'Payment Status (PAID)',
                    'billing.total_amount_display' => 'Total Amount Display',
                    'billing.note' => 'Receipt Note',
                ],
                'Manifest & Consignee' => [
                    'manifest.number' => 'Manifest Number',
                    'manifest.bl_number' => 'BL Number',
                    'consignee.name' => 'Bill To (Consignee Name)',
                    'consignee.email' => 'Consignee Email',
                    'consignee.address' => 'Consignee Address',
                    'broker.name' => 'Broker Name',
                    'broker.email' => 'Broker Email',
                ],
                'Company' => [
                    'company.name' => 'Company Name',
                    'company.address' => 'Company Address',
                    'company.phone' => 'Company Phone',
                    'company.email' => 'Company Email',
                ],
                'System' => [
                    'generated.date' => 'Generated Date',
                    'generated.by' => 'Generated By',
                    'document.verification_url' => 'Verification Link (QR Code)',
                ],
                'Tables' => [
                    'charges.table' => 'Charges Table',
                ],
            ],
            DocumentTemplateType::CERTIFICATE => [
                'Document' => [
                    'certificate.title' => 'Certificate Title',
                    'certificate.recipient' => 'Recipient Name',
                    'certificate.date' => 'Certificate Date',
                    'certificate.reference' => 'Reference Number',
                ],
                'System' => [
                    'generated.date' => 'Generated Date',
                    'company.name' => 'Company Name',
                    'document.verification_url' => 'Verification Link (QR Code)',
                ],
            ],
        };
    }

    public static function defaultCanvas(): array
    {
        return [
            'width' => 794,
            'height' => 1123,
            'paperSize' => 'A4',
            'orientation' => 'portrait',
            'layoutMode' => 'free',
            'backgroundColor' => '#ffffff',
            'margin' => ['top' => 48, 'right' => 48, 'bottom' => 48, 'left' => 48],
            'borderColor' => '#1e3a5f',
            'showPageBorder' => true,
            'showMarginGuides' => true,
        ];
    }

    public static function defaultLayout(DocumentTemplateType $type): array
    {
        $canvas = self::defaultCanvas();

        if ($type === DocumentTemplateType::OFFICIAL_RECEIPT) {
            return OfficialReceiptLayoutAdapter::adapt(self::defaultLayout(DocumentTemplateType::BILLING));
        }

        return match ($type) {
            DocumentTemplateType::NOA => [
                'canvas' => $canvas,
                'elements' => [
                    self::makeElement('header_banner', 1, [
                        'content' => 'NOTICE OF ARRIVAL',
                        'subtitle' => 'Official Shipping Document',
                        'style' => ['textAlign' => 'center', 'backgroundColor' => '#1e3a5f', 'color' => '#ffffff', 'fontSize' => 22, 'padding' => 24],
                    ]),
                    self::makeElement('field_label', 2, [
                        'label' => 'NOA Number',
                        'position' => ['x' => 48, 'y' => 200, 'width' => 250],
                        'style' => ['fontSize' => 11, 'fontWeight' => 'bold', 'color' => '#374151', 'marginBottom' => 0],
                    ]),
                    self::makeElement('field_value', 3, [
                        'placeholder' => 'noa.number',
                        'position' => ['x' => 310, 'y' => 200, 'width' => 436],
                        'style' => ['fontSize' => 11, 'color' => '#1e3a5f', 'marginBottom' => 0],
                    ]),
                    self::makeElement('field_label', 4, [
                        'label' => 'BL Number',
                        'position' => ['x' => 48, 'y' => 232, 'width' => 250],
                        'style' => ['fontSize' => 11, 'fontWeight' => 'bold', 'color' => '#374151', 'marginBottom' => 0],
                    ]),
                    self::makeElement('field_value', 5, [
                        'placeholder' => 'noa.bl_number',
                        'position' => ['x' => 310, 'y' => 232, 'width' => 436],
                        'style' => ['fontSize' => 11, 'color' => '#1e3a5f', 'marginBottom' => 0],
                    ]),
                    self::makeElement('field_label', 6, [
                        'label' => 'Vessel',
                        'position' => ['x' => 48, 'y' => 264, 'width' => 250],
                        'style' => ['fontSize' => 11, 'fontWeight' => 'bold', 'color' => '#374151', 'marginBottom' => 0],
                    ]),
                    self::makeElement('field_value', 7, [
                        'placeholder' => 'noa.vessel_number',
                        'position' => ['x' => 310, 'y' => 264, 'width' => 436],
                        'style' => ['fontSize' => 11, 'color' => '#1e3a5f', 'marginBottom' => 0],
                    ]),
                    self::makeElement('field_label', 8, [
                        'label' => 'ETA',
                        'position' => ['x' => 48, 'y' => 296, 'width' => 250],
                        'style' => ['fontSize' => 11, 'fontWeight' => 'bold', 'color' => '#374151', 'marginBottom' => 0],
                    ]),
                    self::makeElement('field_value', 9, [
                        'placeholder' => 'noa.eta',
                        'position' => ['x' => 310, 'y' => 296, 'width' => 436],
                        'style' => ['fontSize' => 11, 'color' => '#1e3a5f', 'marginBottom' => 0],
                    ]),
                    self::makeElement('field_label', 10, [
                        'label' => 'Port Location',
                        'position' => ['x' => 48, 'y' => 328, 'width' => 250],
                        'style' => ['fontSize' => 11, 'fontWeight' => 'bold', 'color' => '#374151', 'marginBottom' => 0],
                    ]),
                    self::makeElement('field_value', 11, [
                        'placeholder' => 'noa.port_location',
                        'position' => ['x' => 310, 'y' => 328, 'width' => 436],
                        'style' => ['fontSize' => 11, 'color' => '#1e3a5f', 'marginBottom' => 0],
                    ]),
                    self::makeElement('divider', 12, ['style' => ['marginTop' => 16, 'marginBottom' => 16]]),
                    self::makeElement('heading', 13, [
                        'content' => 'Consignee Information',
                        'style' => ['fontSize' => 16, 'fontWeight' => 'bold', 'color' => '#1e3a5f'],
                    ]),
                    self::makeElement('field_label', 14, [
                        'label' => 'Consignee',
                        'position' => ['x' => 48, 'y' => 420, 'width' => 250],
                        'style' => ['fontSize' => 11, 'fontWeight' => 'bold', 'color' => '#374151', 'marginBottom' => 0],
                    ]),
                    self::makeElement('field_value', 15, [
                        'placeholder' => 'consignee.name',
                        'position' => ['x' => 310, 'y' => 420, 'width' => 436],
                        'style' => ['fontSize' => 11, 'color' => '#1e3a5f', 'marginBottom' => 0],
                    ]),
                    self::makeElement('spacer', 16, ['height' => 16]),
                    self::makeElement('heading', 17, [
                        'content' => 'Container Details',
                        'style' => ['fontSize' => 16, 'fontWeight' => 'bold', 'color' => '#1e3a5f'],
                    ]),
                    self::makeElement('table', 18, [
                        'placeholder' => 'containers.table',
                        'columns' => ['Container No.', 'Type', 'Size', 'TEU'],
                    ]),
                    self::makeElement('spacer', 19, ['height' => 32]),
                    self::makeElement('footer', 20, [
                        'content' => 'Generated on {{ generated.date }} by {{ generated.by }}',
                        'style' => ['textAlign' => 'center', 'fontSize' => 10, 'color' => '#666666'],
                    ]),
                ],
            ],
            DocumentTemplateType::MANIFEST_BL => [
                'canvas' => $canvas,
                'elements' => [
                    self::makeElement('header_banner', 1, [
                        'content' => 'MANIFEST / BILL OF LADING',
                        'subtitle' => 'Confirmed Shipping Document',
                        'style' => ['textAlign' => 'center', 'backgroundColor' => '#1e3a5f', 'color' => '#ffffff', 'fontSize' => 22, 'padding' => 24],
                    ]),
                    self::makeElement('field_label', 2, [
                        'label' => 'Manifest Number',
                        'position' => ['x' => 48, 'y' => 200, 'width' => 250],
                        'style' => ['fontSize' => 11, 'fontWeight' => 'bold', 'color' => '#374151', 'marginBottom' => 0],
                    ]),
                    self::makeElement('field_value', 3, [
                        'placeholder' => 'manifest.number',
                        'position' => ['x' => 310, 'y' => 200, 'width' => 436],
                        'style' => ['fontSize' => 11, 'color' => '#1e3a5f', 'marginBottom' => 0],
                    ]),
                    self::makeElement('field_label', 4, [
                        'label' => 'Issue Date',
                        'position' => ['x' => 48, 'y' => 232, 'width' => 250],
                        'style' => ['fontSize' => 11, 'fontWeight' => 'bold', 'color' => '#374151', 'marginBottom' => 0],
                    ]),
                    self::makeElement('field_value', 5, [
                        'placeholder' => 'manifest.issue_date',
                        'position' => ['x' => 310, 'y' => 232, 'width' => 436],
                        'style' => ['fontSize' => 11, 'color' => '#1e3a5f', 'marginBottom' => 0],
                    ]),
                    self::makeElement('field_label', 6, [
                        'label' => 'NOA Number',
                        'position' => ['x' => 48, 'y' => 264, 'width' => 250],
                        'style' => ['fontSize' => 11, 'fontWeight' => 'bold', 'color' => '#374151', 'marginBottom' => 0],
                    ]),
                    self::makeElement('field_value', 7, [
                        'placeholder' => 'noa.number',
                        'position' => ['x' => 310, 'y' => 264, 'width' => 436],
                        'style' => ['fontSize' => 11, 'color' => '#1e3a5f', 'marginBottom' => 0],
                    ]),
                    self::makeElement('field_label', 8, [
                        'label' => 'BL Number',
                        'position' => ['x' => 48, 'y' => 296, 'width' => 250],
                        'style' => ['fontSize' => 11, 'fontWeight' => 'bold', 'color' => '#374151', 'marginBottom' => 0],
                    ]),
                    self::makeElement('field_value', 9, [
                        'placeholder' => 'noa.bl_number',
                        'position' => ['x' => 310, 'y' => 296, 'width' => 436],
                        'style' => ['fontSize' => 11, 'color' => '#1e3a5f', 'marginBottom' => 0],
                    ]),
                    self::makeElement('field_label', 10, [
                        'label' => 'Vessel',
                        'position' => ['x' => 48, 'y' => 328, 'width' => 250],
                        'style' => ['fontSize' => 11, 'fontWeight' => 'bold', 'color' => '#374151', 'marginBottom' => 0],
                    ]),
                    self::makeElement('field_value', 11, [
                        'placeholder' => 'noa.vessel_number',
                        'position' => ['x' => 310, 'y' => 328, 'width' => 436],
                        'style' => ['fontSize' => 11, 'color' => '#1e3a5f', 'marginBottom' => 0],
                    ]),
                    self::makeElement('field_label', 12, [
                        'label' => 'Arrival Date',
                        'position' => ['x' => 48, 'y' => 360, 'width' => 250],
                        'style' => ['fontSize' => 11, 'fontWeight' => 'bold', 'color' => '#374151', 'marginBottom' => 0],
                    ]),
                    self::makeElement('field_value', 13, [
                        'placeholder' => 'manifest.arrival_date',
                        'position' => ['x' => 310, 'y' => 360, 'width' => 436],
                        'style' => ['fontSize' => 11, 'color' => '#1e3a5f', 'marginBottom' => 0],
                    ]),
                    self::makeElement('field_label', 14, [
                        'label' => 'Port Location',
                        'position' => ['x' => 48, 'y' => 392, 'width' => 250],
                        'style' => ['fontSize' => 11, 'fontWeight' => 'bold', 'color' => '#374151', 'marginBottom' => 0],
                    ]),
                    self::makeElement('field_value', 15, [
                        'placeholder' => 'noa.port_location',
                        'position' => ['x' => 310, 'y' => 392, 'width' => 436],
                        'style' => ['fontSize' => 11, 'color' => '#1e3a5f', 'marginBottom' => 0],
                    ]),
                    self::makeElement('divider', 16, ['style' => ['marginTop' => 16, 'marginBottom' => 16]]),
                    self::makeElement('heading', 17, [
                        'content' => 'Consignee Information',
                        'style' => ['fontSize' => 16, 'fontWeight' => 'bold', 'color' => '#1e3a5f'],
                    ]),
                    self::makeElement('field_label', 18, [
                        'label' => 'Consignee',
                        'position' => ['x' => 48, 'y' => 484, 'width' => 250],
                        'style' => ['fontSize' => 11, 'fontWeight' => 'bold', 'color' => '#374151', 'marginBottom' => 0],
                    ]),
                    self::makeElement('field_value', 19, [
                        'placeholder' => 'consignee.name',
                        'position' => ['x' => 310, 'y' => 484, 'width' => 436],
                        'style' => ['fontSize' => 11, 'color' => '#1e3a5f', 'marginBottom' => 0],
                    ]),
                    self::makeElement('spacer', 20, ['height' => 16]),
                    self::makeElement('heading', 21, [
                        'content' => 'Container Details',
                        'style' => ['fontSize' => 16, 'fontWeight' => 'bold', 'color' => '#1e3a5f'],
                    ]),
                    self::makeElement('table', 22, [
                        'placeholder' => 'containers.table',
                        'columns' => ['Container No.', 'Type', 'Size', 'TEU'],
                    ]),
                    self::makeElement('spacer', 23, ['height' => 32]),
                    self::makeElement('footer', 24, [
                        'content' => 'Generated on {{ generated.date }} by {{ generated.by }}',
                        'style' => ['textAlign' => 'center', 'fontSize' => 10, 'color' => '#666666'],
                    ]),
                ],
            ],
            DocumentTemplateType::BILLING => [
                'canvas' => $canvas,
                'elements' => [
                    self::makeElement('heading', 1, [
                        'content' => 'Invoice',
                        'position' => ['x' => 48, 'y' => 40, 'width' => 220],
                        'style' => ['fontSize' => 28, 'fontWeight' => 'bold', 'color' => '#2962ff', 'marginBottom' => 0],
                    ]),
                    self::makeElement('border_box', 2, [
                        'content' => '{{ company.name }}',
                        'position' => ['x' => 470, 'y' => 40, 'width' => 276],
                        'style' => ['fontSize' => 14, 'fontWeight' => 'bold', 'textAlign' => 'center', 'borderColor' => '#000000', 'borderWidth' => 1, 'padding' => 10],
                    ]),
                    self::makeElement('field_value', 3, [
                        'placeholder' => 'company.address',
                        'position' => ['x' => 470, 'y' => 88, 'width' => 276],
                        'style' => ['fontSize' => 9, 'textAlign' => 'right', 'marginBottom' => 0, 'color' => '#374151'],
                    ]),
                    self::makeElement('info_row', 4, [
                        'label' => 'INVOICE No:',
                        'placeholder' => 'billing.invoice_number',
                        'position' => ['x' => 48, 'y' => 96, 'width' => 360],
                    ]),
                    self::makeElement('info_row', 5, [
                        'label' => 'DATE:',
                        'placeholder' => 'billing.invoice_date',
                        'position' => ['x' => 48, 'y' => 120, 'width' => 360],
                    ]),
                    self::makeElement('info_row', 6, [
                        'label' => 'INVOICE DUE DATE:',
                        'placeholder' => 'billing.due_date',
                        'position' => ['x' => 48, 'y' => 144, 'width' => 360],
                    ]),
                    self::makeElement('info_row', 7, [
                        'label' => 'BILL TO:',
                        'placeholder' => 'consignee.name',
                        'position' => ['x' => 48, 'y' => 184, 'width' => 360],
                    ]),
                    self::makeElement('info_row', 8, [
                        'label' => 'Address:',
                        'placeholder' => 'consignee.address',
                        'position' => ['x' => 48, 'y' => 208, 'width' => 360],
                    ]),
                    self::makeElement('field_label', 9, [
                        'label' => 'Amount',
                        'position' => ['x' => 470, 'y' => 184, 'width' => 276],
                        'style' => ['fontSize' => 10, 'fontWeight' => 'bold', 'textAlign' => 'right', 'marginBottom' => 0, 'color' => '#374151'],
                    ]),
                    self::makeElement('field_value', 10, [
                        'placeholder' => 'billing.amount_primary',
                        'position' => ['x' => 470, 'y' => 202, 'width' => 276],
                        'style' => ['fontSize' => 14, 'fontWeight' => 'bold', 'textAlign' => 'right', 'marginBottom' => 0],
                    ]),
                    self::makeElement('field_value', 11, [
                        'placeholder' => 'billing.amount_secondary',
                        'position' => ['x' => 470, 'y' => 222, 'width' => 276],
                        'style' => ['fontSize' => 10, 'textAlign' => 'right', 'marginBottom' => 0, 'color' => '#6b7280'],
                    ]),
                    self::makeElement('border_box', 12, [
                        'content' => '{{ billing.status }}',
                        'position' => ['x' => 470, 'y' => 248, 'width' => 276],
                        'style' => ['fontSize' => 12, 'fontWeight' => 'bold', 'textAlign' => 'center', 'backgroundColor' => '#dc3545', 'borderColor' => '#dc3545', 'borderWidth' => 1, 'color' => '#ffffff', 'padding' => 8],
                    ]),
                    self::makeElement('info_row', 13, [
                        'label' => 'Email:',
                        'placeholder' => 'consignee.email',
                        'position' => ['x' => 48, 'y' => 236, 'width' => 400],
                    ]),
                    self::makeElement('divider', 14, ['position' => ['x' => 48, 'y' => 272, 'width' => 698], 'style' => ['marginTop' => 4, 'marginBottom' => 4]]),
                    self::makeElement('info_row', 15, [
                        'label' => 'Manifest Number:',
                        'placeholder' => 'manifest.number',
                        'position' => ['x' => 48, 'y' => 292, 'width' => 698],
                    ]),
                    self::makeElement('info_row', 16, [
                        'label' => 'BL Number:',
                        'placeholder' => 'manifest.bl_number',
                        'position' => ['x' => 48, 'y' => 316, 'width' => 698],
                    ]),
                    self::makeElement('info_row', 17, [
                        'label' => 'Exchange Rate:',
                        'placeholder' => 'billing.exchange_rate_display',
                        'position' => ['x' => 48, 'y' => 340, 'width' => 698],
                    ]),
                    self::makeElement('table', 18, [
                        'placeholder' => 'charges.table',
                        'columns' => ['#', 'DESCRIPTION OF CHARGES', 'AMOUNT', 'TAX'],
                        'position' => ['x' => 48, 'y' => 372, 'width' => 698],
                    ]),
                    self::makeElement('field_label', 19, [
                        'label' => 'NOTE:',
                        'position' => ['x' => 48, 'y' => 580, 'width' => 80],
                        'style' => ['fontSize' => 10, 'fontWeight' => 'bold', 'marginBottom' => 0],
                    ]),
                    self::makeElement('field_value', 20, [
                        'placeholder' => 'billing.note',
                        'position' => ['x' => 48, 'y' => 600, 'width' => 400],
                        'style' => ['fontSize' => 9, 'marginBottom' => 0, 'color' => '#374151'],
                    ]),
                    self::makeElement('field_label', 21, [
                        'label' => 'TOTAL',
                        'position' => ['x' => 500, 'y' => 580, 'width' => 120],
                        'style' => ['fontSize' => 12, 'fontWeight' => 'bold', 'textAlign' => 'right', 'marginBottom' => 0],
                    ]),
                    self::makeElement('field_value', 22, [
                        'placeholder' => 'billing.total_amount_display',
                        'position' => ['x' => 500, 'y' => 600, 'width' => 246],
                        'style' => ['fontSize' => 22, 'fontWeight' => 'bold', 'textAlign' => 'right', 'marginBottom' => 0],
                    ]),
                    self::makeElement('field_value', 23, [
                        'placeholder' => 'billing.total_amount_usd',
                        'position' => ['x' => 500, 'y' => 632, 'width' => 246],
                        'style' => ['fontSize' => 10, 'textAlign' => 'right', 'marginBottom' => 0, 'color' => '#6b7280'],
                    ]),
                    self::makeElement('footer', 24, [
                        'content' => 'Generated by: {{ generated.by }}',
                        'position' => ['x' => 48, 'y' => 680, 'width' => 400],
                        'style' => ['textAlign' => 'left', 'fontSize' => 8, 'color' => '#808080'],
                    ]),
                    self::makeElement('footer', 25, [
                        'content' => 'Generated on: {{ generated.date }}',
                        'position' => ['x' => 48, 'y' => 698, 'width' => 400],
                        'style' => ['textAlign' => 'left', 'fontSize' => 8, 'color' => '#808080'],
                    ]),
                ],
            ],
            DocumentTemplateType::EDO => self::defaultEdoLayout(),
            default => [
                'canvas' => $canvas,
                'elements' => [
                    self::makeElement('header_banner', 1, [
                        'content' => $type->getLabel(),
                        'subtitle' => 'Document Template',
                        'style' => ['textAlign' => 'center', 'backgroundColor' => '#1e3a5f', 'color' => '#ffffff', 'fontSize' => 20, 'padding' => 20],
                    ]),
                    self::makeElement('text', 2, [
                        'content' => 'Design your document by adding elements from the palette.',
                        'style' => ['textAlign' => 'center', 'fontSize' => 12, 'color' => '#444444'],
                    ]),
                ],
            ],
        };
    }

    /**
     * @return array{canvas: array<string, mixed>, elements: array<int, array<string, mixed>>}
     */
    public static function defaultEdoLayout(): array
    {
        $canvas = array_merge(self::defaultCanvas(), [
            'orientation' => 'landscape',
            'width' => 1123,
            'height' => 794,
            'paperSize' => 'A4',
            'layoutMode' => 'free',
            'margin' => ['top' => 24, 'right' => 24, 'bottom' => 24, 'left' => 24],
            'showPageBorder' => false,
            'showMarginGuides' => false,
        ]);

        $contentWidth = 1075;

        return [
            'canvas' => $canvas,
            'elements' => [
                self::makeElement('border_box', 1, [
                    'content' => ' ',
                    'position' => ['x' => 24, 'y' => 24, 'width' => $contentWidth, 'height' => 72],
                    'style' => ['backgroundColor' => '#0f172a', 'borderColor' => '#0f172a', 'borderWidth' => 0, 'padding' => 0],
                ]),
                self::makeElement('field_label', 2, [
                    'label' => '{{ platform.brand }}',
                    'position' => ['x' => 48, 'y' => 36, 'width' => 320],
                    'style' => ['fontSize' => 20, 'fontWeight' => 'bold', 'color' => '#ffffff', 'marginBottom' => 0, 'letterSpacing' => 3],
                ]),
                self::makeElement('field_label', 3, [
                    'label' => '{{ platform.tagline }}',
                    'position' => ['x' => 48, 'y' => 62, 'width' => 360],
                    'style' => ['fontSize' => 8, 'fontWeight' => 'bold', 'color' => '#3b82f6', 'marginBottom' => 0, 'letterSpacing' => 1],
                ]),
                self::makeElement('field_label', 4, [
                    'label' => '{{ edo.document_title }}',
                    'position' => ['x' => 620, 'y' => 40, 'width' => 460],
                    'style' => ['fontSize' => 13, 'fontWeight' => 'normal', 'color' => '#ffffff', 'textAlign' => 'right', 'marginBottom' => 0],
                ]),
                self::makeElement('field_label', 5, [
                    'label' => '{{ edo.document_subtitle }}',
                    'position' => ['x' => 620, 'y' => 60, 'width' => 460],
                    'style' => ['fontSize' => 11, 'fontWeight' => 'normal', 'color' => '#ffffff', 'textAlign' => 'right', 'marginBottom' => 0],
                ]),
                self::makeElement('border_box', 6, [
                    'content' => ' ',
                    'position' => ['x' => 24, 'y' => 104, 'width' => $contentWidth, 'height' => 44],
                    'style' => ['backgroundColor' => '#f8fafc', 'borderColor' => '#e2e8f0', 'borderWidth' => 1, 'padding' => 0],
                ]),
                self::makeElement('field_label', 7, [
                    'label' => 'BL NUMBER',
                    'position' => ['x' => 48, 'y' => 112, 'width' => 300],
                    'style' => ['fontSize' => 8, 'fontWeight' => 'bold', 'color' => '#64748b', 'marginBottom' => 0],
                ]),
                self::makeElement('field_value', 8, [
                    'placeholder' => 'manifest.bl_number',
                    'position' => ['x' => 48, 'y' => 126, 'width' => 300],
                    'style' => ['fontSize' => 11, 'fontWeight' => 'bold', 'color' => '#0f172a', 'marginBottom' => 0],
                ]),
                self::makeElement('field_label', 9, [
                    'label' => 'REGISTRY NUMBER',
                    'position' => ['x' => 400, 'y' => 112, 'width' => 300],
                    'style' => ['fontSize' => 8, 'fontWeight' => 'bold', 'color' => '#64748b', 'textAlign' => 'center', 'marginBottom' => 0],
                ]),
                self::makeElement('field_value', 10, [
                    'placeholder' => 'noa.number',
                    'position' => ['x' => 400, 'y' => 126, 'width' => 300],
                    'style' => ['fontSize' => 11, 'fontWeight' => 'bold', 'color' => '#0f172a', 'textAlign' => 'center', 'marginBottom' => 0],
                ]),
                self::makeElement('field_label', 11, [
                    'label' => 'MANIFEST NUMBER',
                    'position' => ['x' => 760, 'y' => 112, 'width' => 300],
                    'style' => ['fontSize' => 8, 'fontWeight' => 'bold', 'color' => '#64748b', 'textAlign' => 'right', 'marginBottom' => 0],
                ]),
                self::makeElement('field_value', 12, [
                    'placeholder' => 'manifest.number',
                    'position' => ['x' => 760, 'y' => 126, 'width' => 300],
                    'style' => ['fontSize' => 11, 'fontWeight' => 'bold', 'color' => '#0f172a', 'textAlign' => 'right', 'marginBottom' => 0],
                ]),
                self::makeElement('divider', 13, [
                    'position' => ['x' => 24, 'y' => 156, 'width' => $contentWidth],
                    'style' => ['marginTop' => 0, 'marginBottom' => 0],
                ]),
                self::makeElement('field_label', 14, [
                    'label' => 'CONSIGNEE/NOTIFY PARTY',
                    'position' => ['x' => 48, 'y' => 168, 'width' => 400],
                    'style' => ['fontSize' => 8, 'fontWeight' => 'bold', 'color' => '#64748b', 'marginBottom' => 0],
                ]),
                self::makeElement('field_value', 15, [
                    'placeholder' => 'consignee.name',
                    'position' => ['x' => 48, 'y' => 184, 'width' => 700],
                    'style' => ['fontSize' => 16, 'fontWeight' => 'bold', 'color' => '#0f172a', 'marginBottom' => 0],
                ]),
                self::makeElement('info_row', 16, [
                    'label' => 'SHIPPING LINE/CARRIER:',
                    'placeholder' => 'shipping.line',
                    'position' => ['x' => 48, 'y' => 220, 'width' => 500],
                ]),
                self::makeElement('info_row', 17, [
                    'label' => 'VESSEL/VOYAGE NUMBER:',
                    'placeholder' => 'vessel.display',
                    'position' => ['x' => 560, 'y' => 220, 'width' => 520],
                ]),
                self::makeElement('info_row', 18, [
                    'label' => 'NAME OF BROKER:',
                    'placeholder' => 'broker.name',
                    'position' => ['x' => 48, 'y' => 248, 'width' => 500],
                ]),
                self::makeElement('info_row', 19, [
                    'label' => 'DOCUMENT STATUS:',
                    'placeholder' => 'edo.status',
                    'position' => ['x' => 560, 'y' => 248, 'width' => 520],
                ]),
                self::makeElement('info_row', 20, [
                    'label' => 'PRINT DATE/TIME:',
                    'placeholder' => 'generated.date',
                    'position' => ['x' => 48, 'y' => 276, 'width' => 500],
                ]),
                self::makeElement('table', 21, [
                    'placeholder' => 'containers.table',
                    'columns' => [
                        'NO.',
                        'CONTAINER NUMBER',
                        'SIZE',
                        'TYPE',
                        'SEAL',
                        'NAME OF HAULER',
                        'PLATE NO.',
                        'OPTIMUS REF NO.',
                        'DEMURRAGE VALIDITY',
                        'RETURN EMPTY TO',
                    ],
                    'columnWidths' => [4, 11, 7, 5, 5, 11, 7, 14, 11, 25],
                    'position' => ['x' => 24, 'y' => 310, 'width' => $contentWidth],
                ]),
                self::makeElement('field_label', 22, [
                    'label' => 'PORT OPERATIONS DIRECTIVE:',
                    'position' => ['x' => 48, 'y' => 520, 'width' => $contentWidth],
                    'style' => ['fontSize' => 10, 'fontWeight' => 'bold', 'color' => '#0f172a', 'marginBottom' => 0],
                ]),
                self::makeElement('text', 23, [
                    'content' => '{{ edo.port_directive }}',
                    'position' => ['x' => 48, 'y' => 538, 'width' => 1000],
                    'style' => ['fontSize' => 9, 'color' => '#334155', 'lineHeight' => 1.5],
                ]),
                self::makeElement('divider', 24, [
                    'position' => ['x' => 24, 'y' => 610, 'width' => $contentWidth],
                    'style' => ['marginTop' => 8, 'marginBottom' => 8],
                ]),
                self::makeElement('field_label', 25, [
                    'label' => '{{ signatures.authorized_title }}',
                    'position' => ['x' => 48, 'y' => 630, 'width' => 300],
                    'style' => ['fontSize' => 8, 'fontWeight' => 'bold', 'color' => '#64748b', 'marginBottom' => 0],
                ]),
                self::makeElement('field_value', 26, [
                    'placeholder' => 'signatures.authorized_company',
                    'position' => ['x' => 48, 'y' => 660, 'width' => 300],
                    'style' => ['fontSize' => 10, 'fontWeight' => 'bold', 'color' => '#0f172a', 'marginBottom' => 0],
                ]),
                self::makeElement('field_label', 27, [
                    'label' => '{{ signatures.prepared_title }}',
                    'position' => ['x' => 400, 'y' => 630, 'width' => 300],
                    'style' => ['fontSize' => 8, 'fontWeight' => 'bold', 'color' => '#64748b', 'textAlign' => 'center', 'marginBottom' => 0],
                ]),
                self::makeElement('field_value', 28, [
                    'placeholder' => 'signatures.prepared_by',
                    'position' => ['x' => 400, 'y' => 660, 'width' => 300],
                    'style' => ['fontSize' => 10, 'fontWeight' => 'bold', 'color' => '#0f172a', 'textAlign' => 'center', 'marginBottom' => 0],
                ]),
                self::makeElement('field_label', 29, [
                    'label' => '{{ signatures.received_title }}',
                    'position' => ['x' => 760, 'y' => 630, 'width' => 300],
                    'style' => ['fontSize' => 8, 'fontWeight' => 'bold', 'color' => '#64748b', 'textAlign' => 'right', 'marginBottom' => 0],
                ]),
                self::makeElement('field_value', 30, [
                    'placeholder' => 'generated.date',
                    'position' => ['x' => 760, 'y' => 660, 'width' => 300],
                    'style' => ['fontSize' => 10, 'color' => '#0f172a', 'textAlign' => 'right', 'marginBottom' => 0],
                ]),
            ],
        ];
    }

    public static function makeElement(string $type, int $order, array $config = []): array
    {
        return array_merge([
            'id' => self::generateId(),
            'type' => $type,
            'order' => $order,
            'content' => '',
            'placeholder' => '',
            'label' => '',
            'style' => [
                'fontSize' => 12,
                'fontWeight' => 'normal',
                'textAlign' => 'left',
                'color' => '#000000',
                'backgroundColor' => 'transparent',
                'padding' => 0,
                'marginTop' => 0,
                'marginRight' => 0,
                'marginBottom' => 8,
                'marginLeft' => 0,
            ],
            'position' => ['x' => 48, 'y' => 48, 'width' => 698],
            'config' => [],
        ], $config);
    }

    public static function defaultElementForType(string $blockType): array
    {
        $defaults = match ($blockType) {
            'header_banner' => [
                'content' => 'Document Title',
                'subtitle' => 'Subtitle',
                'style' => ['textAlign' => 'center', 'backgroundColor' => '#1e3a5f', 'color' => '#ffffff', 'fontSize' => 20, 'padding' => 20],
            ],
            'heading' => [
                'content' => 'Section Heading',
                'style' => ['fontSize' => 16, 'fontWeight' => 'bold', 'color' => '#1e3a5f'],
            ],
            'text' => [
                'content' => 'Enter your text here...',
                'style' => ['fontSize' => 12],
            ],
            'placeholder' => [
                'placeholder' => 'noa.number',
            ],
            'field_label' => [
                'label' => 'Label',
                'style' => ['fontSize' => 11, 'fontWeight' => 'bold', 'color' => '#374151'],
            ],
            'field_value' => [
                'placeholder' => 'noa.number',
                'style' => ['fontSize' => 11, 'color' => '#1e3a5f'],
            ],
            'info_row' => [
                'label' => 'Label',
                'placeholder' => 'noa.number',
            ],
            'divider' => [
                'dividerStyle' => 'solid',
                'height' => 24,
                'slashWeight' => 'medium',
                'slashCount' => 5,
                'style' => ['marginTop' => 12, 'marginBottom' => 12, 'color' => '#374151', 'borderColor' => '#6366f1', 'borderWidth' => 1],
            ],
            'spacer' => [
                'height' => 24,
            ],
            'table' => [
                'placeholder' => 'containers.table',
                'columns' => ['Column 1', 'Column 2', 'Column 3'],
            ],
            'signature' => [
                'label' => 'Authorized Signature',
                'style' => ['textAlign' => 'center'],
            ],
            'qr_code' => [
                'placeholder' => 'document.verification_url',
                'size' => 80,
            ],
            'border_box' => [
                'content' => 'Certificate content area',
                'style' => ['borderColor' => '#1e3a5f', 'borderWidth' => 2, 'backgroundColor' => '#ffffff', 'color' => '#1e3a5f', 'padding' => 24, 'textAlign' => 'center'],
            ],
            'two_column' => [
                'leftContent' => 'Left column content',
                'rightContent' => 'Right column content',
            ],
            'footer' => [
                'content' => 'Footer text — {{ generated.date }}',
                'style' => ['textAlign' => 'center', 'fontSize' => 10, 'color' => '#666666'],
            ],
            'logo', 'image' => [
                'config' => ['src' => '', 'alt' => 'Logo', 'width' => 120],
            ],
            default => [],
        };

        return self::makeElement($blockType, 0, $defaults);
    }

    public static function generateId(): string
    {
        return 'el_' . bin2hex(random_bytes(8));
    }

    /**
     * @param array<string, mixed> $element
     * @return array<string, mixed>
     */
    public static function normalizeTableElement(array $element): array
    {
        if (($element['type'] ?? '') !== 'table') {
            return $element;
        }

        $columns = $element['columns'] ?? [];
        if (!is_array($columns)) {
            $columns = [];
        }

        $element['columnWidths'] = self::computeTableColumnWidths(
            $columns,
            is_array($element['columnWidths'] ?? null) ? $element['columnWidths'] : null,
        );

        return $element;
    }

    /**
     * @param array<int, string> $columns
     * @param array<int, float|int|string>|null $rawWidths
     * @return array<int, float>
     */
    public static function computeTableColumnWidths(array $columns, ?array $rawWidths): array
    {
        $count = count($columns);
        if ($count === 0) {
            return [];
        }

        $widths = [];
        if ($rawWidths !== null) {
            foreach ($rawWidths as $width) {
                $parsed = is_numeric($width) ? (float) $width : 0.0;
                if ($parsed > 0) {
                    $widths[] = $parsed;
                }
            }
        }

        if (count($widths) === $count) {
            $sum = array_sum($widths);
            if ($sum > 0) {
                $normalized = array_map(
                    static fn (float $width): float => round(($width / $sum) * 100, 1),
                    $widths,
                );
                $remainder = round(100 - array_sum($normalized), 1);
                $normalized[$count - 1] = round($normalized[$count - 1] + $remainder, 1);

                return $normalized;
            }
        }

        $base = round((100 / $count) * 10) / 10;
        $normalized = [];
        for ($index = 0; $index < $count; ++$index) {
            $normalized[] = $index === $count - 1
                ? round(100 - ($base * ($count - 1)), 1)
                : $base;
        }

        return $normalized;
    }
}
